services:
  db:
    image: postgres:16-alpine
    container_name: products_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products_db
    ports:
      - "5434:5432"
    volumes:
      - products_db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d products_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  products_db: